config/routes.rb
Rails.application.routes.draw do
  root to: 'routing#root', via: :get

  devise_for :users, skip: [:sessions]
  devise_scope :user do
    # Override paths for login/logout to have simpler paths.
    get 'signin', to: 'devise/sessions#new', as: :new_user_session
    post 'signin', to: 'devise/sessions#create', as: :user_session
    delete 'signout', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  resources :authorities
  resources :pages
  resources :paths
  resources :roles
  resources :users do
    member do
      get 'unlock', action: :unlock_form
      patch 'unlock', action: :unlock
    end
  end

  get 'about' => 'routing#about'
  get 'fresh_install' => 'routing#fresh_install'
  post 'create_initial_records' => 'routing#create_initial_records'
  get '*url' => 'routing#sitepath', format: false
end

app/models/user.rb
# User Access.
# Managed using the Devise gem http://devise.plataformatec.com.br/
class User < ApplicationRecord
  # Include devise modules. (except for )
  devise(
    :database_authenticatable, # password-based authentication for signing in.
    :registerable, # user registration process, and account edit or destroy.
    # :omniauthable, # OmniAuth (https://github.com/omniauth/omniauth) support.
    :confirmable, # confirmation of email address.
    :lockable, # locks an account after a specified number of failed sign-in attempts.
    # :timeoutable, # expires sessions that have not been active in a specified period of time.
    :recoverable, # resets the user password and sends reset instructions.
    :rememberable, # manages token for remembering the user from a saved cookie.
    :trackable, # tracks sign in count, timestamps and IP address.
    :validatable # provides validations of email and password.
  )

  has_many :authorities, dependent: :destroy

  validates :name, presence: true

  def descriptor
    name
  end
end

app/controllers/users_controller.rb
# Creation and management of Users.
class UsersController < ApplicationController
  before_action :check_can_read, only: %i[index show edit unlock_form]
  before_action :check_can_create, only: %i[new create]
  before_action :check_can_update, only: %i[edit update unlock_form unlock]
  before_action :check_can_destroy, only: %i[delete destroy]
  before_action :set_user, only: %i[show edit update delete destroy unlock_form unlock]

  def index
    @users = User.all
  end

  def show; end

  def new
    @user = User.new
  end

  def edit; end

  def create
    user_params = params.fetch(:user, {}).permit(:name, :email, :password, :password_confirmation)
    @user = User.new(user_params)
    if @user.save
      redirect_to user_url(@user), notice: 'User was successfully created.'
    else
      flash.now.alert = 'Could not save the user with the given values.'
      render :new
    end
  end

  def update
    if @user.update(params.fetch(:user, {}).permit(:name))
      redirect_to user_url(@user), notice: 'User was successfully updated.'
    else
      flash.now.alert = 'Could not update the user with the given values.'
      render :edit
    end
  end

  def delete; end

  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was deleted.'
  end

  def unlock_form; end

  def unlock
    # TODO: raise exception if trying to unlock a user that isn’t locked
    @user.unlock_access!
    redirect_to user_url(@user), notice: 'User was successfully unlocked.'
  end

  protected

  def area
    'system'
  end

  private

  def set_user
    @user = User.find(params.fetch(:id))
  end
end

app/views/users/_form.html.erb
<%
# Requires:
# - user (the user being edited)
# - path (e.g., users_path)
is_new = user.new_record?
-%>
<%= form_with(url: path, model: user, local: true) do |form| %>
<%= show_errors(user) -%>
<table>
<tbody>
<tr><th><%= form.label :name, 'Name' %></th>
  <td><%= form.text_field :name, id: 'user_name' %></td></tr>
<% if is_new -%>
<tr><th><%= form.label :email %></th>
  <td><%= form.email_field :email, id: 'user_email' %></td></tr>
<tr><th><%= form.label :password %></th>
  <td><%= form.password_field :password, id: 'user_password', autocomplete: 'off' %></td></tr>
<tr><th><%= form.label :password_confirmation %></th>
  <td><%= form.password_field :password_confirmation, id: 'user_password_confirmation', autocomplete: 'off' %></td></tr>
<% else -%>
<tr><th>Email</th>
  <td><span title="Cannot change email"><%= user.email %></span></td></tr>
<% end -%>
</tbody>
<tfoot>
<tr><th></th>
  <td><%= form.submit 'Save User' %></td></tr>
</tfoot>
</table>
<% end %>

app/views/users/_header.html.erb
<%
user ||= nil

content_for(:menus) do -%>
<li id="usersadminmenu"><%= link_to 'Users', users_path, title: 'Users administration; manage user access' %><ul>
  <li><%= link_to 'User List', users_path, title: 'List all users' %></li>
  <li><%= link_to 'Add User', new_user_path, title: 'Add a new user' %></li>
  <li class="separator"></li>
<%
  if user -%>
  <%=
    tag.li(link_to(
      'Edit Current User', edit_user_path(user),
      title: "Edit the current user (#{user.descriptor})"
    )) %>
  <%=
    tag.li(link_to(
      'Delete Current User', delete_user_path(user),
      title: "Delete the current user (#{user.descriptor})"
    )) %>
<%  if user.access_locked? -%>
  <%=
    tag.li(link_to(
      'Unlock Current User', unlock_user_path(user),
      title: "Unlock the current user (#{user.descriptor})"
    )) %>
<%  else -%>
  <li class="unavailable" title="User is already unlocked">Unlock Current User</li>
<%
    end
  else -%>
  <li class="unavailable" title="no current user selected">Edit Current User</li>
  <li class="unavailable" title="no current user selected">Delete Current User</li>
  <li class="unavailable" title="no current user selected">Unlock Current User</li>
<%
  end
-%>
  </ul></li>
<%
end

# associated = []
# if user && !user.removed?.present?
#   # Load up the Wayfinder
#   actions = {}
#   actions[:unlock] = unlock_user_path(user) if user.access_locked?
#   actions[:update] = edit_user_path(user)
#   actions[:delete] = delete_user_path(user)
#   actions[:create] = new_user_path
# else
#   actions = { create: new_user_path }
# end
# wayfinder(section: :user, associated: associated, item: user, actions: actions)
-%>

app/views/users/delete.html.erb
<%
user = @user
-%>
<%= render partial: 'header', locals: { user: user } -%>
<h2>Remove User <%= link_to user.descriptor, user_path(user) %></h2>
<p>
This will remove all access and permissions for the user, rendering the account unusable.
<br />But all records of the user’s actions in the system will remain intact.
</p>
<%= form_tag user_path(user), method: :delete do %>
<div class="actions">
<%= submit_tag "Delete User" %>
</div>
<% end %>

app/views/users/edit.html.erb
<%
user = @user
-%>
<%= render partial: 'header', locals: { user: user } -%>
<h2>Editing User <%= link_to user.descriptor, user_path(user) %></h2>

<%= render 'form', user: user, path: user_path(user) %>

app/views/users/index.html.erb
<%
# TODO: make sortable by clicking on column headers (javascript)
# TODO: checkboxes to show/hide suspended, active, admins
-%>
<%= render partial: 'header' -%>
<table>
<thead>
<tr>
<th></th>
<th>User</th>
<th>Name</th>
<th>Email</th>
<th>Confirmed</th>
<th>Signins</th>
<th>Last Signin</th>
<th>Locked?</th>
<th>Actions</th>
</tr>
</thead>
<tbody>
<%
@users.each do |user|
  locked = user.access_locked?
  %><%=
  tag.tr(id: "user_#{user.id}") do %>
<%
  flags = []
  flags << 'locked' if locked
  %><td><%
  # TODO: use lock icon for locked flag; link to action to unlock user
  flags.each do |flag|
    %><%= flag %>: <%
  end
  %></td><%
  %><%= tag.td(class: flags.join(' ')) do %><%
    %><%= link_to user.descriptor, user_path(user) %><%
  end %>
<td class="name"><%= user.name %></td>
<td class="email"><%= user.email %></td>
<%=
  confirmed_at = user.confirmed_at
  if confirmed_at
    tag.td(confirmed_at, class: 'true datetime')
  else
    tag.td('—', class: 'false')
  end
  %>
<td class="numeric"><%= user.sign_in_count %></td>
<td class="datetime"><%= user.last_sign_in_at %></td>
<%=
    if locked
      tag.td(user.locked_at, class: 'icon lock datetime')
    else
      tag.td('', class: 'icon unlock')
    end
  %>
<td>
  <%
    if locked
      %><%= link_to 'Unlock', unlock_user_path(user) %>
  <%
    end
    %><%= link_to 'Edit', edit_user_path(user) %>
  <%= link_to 'Remove', delete_user_path(user) %>
</td>
<%
  end %><%
end
%>
</tbody>
</table>

app/views/users/new.html.erb
<%
user = @user || ::User.new
-%>
<%= render partial: 'header' -%>
<h1>New User</h1>

<%= render 'form', user: user, path: users_path %>

app/views/users/show.html.erb
<%
user = @user
is_locked = user.access_locked?
-%>
<%= render partial: 'header', locals: { user: user } -%>

<p>
<span class="name"><%= user.name %></span>
<br /><span class="icon email"><%= user.email %></span>
</p>

<% if is_locked -%>
<h2>Locked</h2>
<p>
<%= user.failed_attempts %> failed signin attempts.
<br />Locked at <span class="datetime"><%= user.locked_at %>.</span>
</p>
<p>
<%= link_to 'Unlock', unlock_user_path(user), class: 'icon unlock' %>
</p>
<% end -%>

<h2>Signins</h2>
<p>
Signed in <%= user.sign_in_count %> times.
<% if user.sign_in_count > 0 -%>
<br />Current: <span class="datetime"><%= user.current_sign_in_at %></span>
from <span class="ipaddress"><%= user.current_sign_in_ip %></span>
<br />Last: <span class="datetime"><%= user.last_sign_in_at %></span>
from <span class="ipaddress"><%= user.last_sign_in_ip %></span>
<% end -%>
</p>

<%=
render(
  partial: 'authorities/table',
  locals: { authorities: user.authorities, include_new: { user_id: user.id }, exclude_user: true }
)
%>

app/views/users/unlock_form.html.erb
<%
user = @user
-%>
<%= render partial: 'header', locals: { user: user } -%>
<h2>Unlock User <%= link_to user.descriptor, user_path(user) %></h2>
<p>
This will restore signin access for the user, rendering the account usable again.
</p>
<%= form_tag unlock_user_path(user), method: :patch do %>
<div class="actions">
<%= submit_tag "Unlock #{user.descriptor}" %>
</div>
<% end %>