config/routes.rb
Rails.application.routes.draw do
  root to: 'routing#root', via: :get

  devise_for :users, skip: [:sessions]
  devise_scope :user do
    # Override paths for login/logout to have simpler paths.
    get 'signin', to: 'devise/sessions#new', as: :new_user_session
    post 'signin', to: 'devise/sessions#create', as: :user_session
    delete 'signout', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  resources :authorities
  resources :pages
  resources :paths
  resources :roles
  resources :users do
    member do
      get 'unlock', action: :unlock_form
      patch 'unlock', action: :unlock
    end
  end

  get 'about' => 'routing#about'
  get 'fresh_install' => 'routing#fresh_install'
  post 'create_initial_records' => 'routing#create_initial_records'
  get '*url' => 'routing#sitepath', format: false
end

app/views/pages/_form.html.erb
<%= form_with(model: page, local: true) do |form| %>
<%= show_errors(page) %>
<table>
<tbody>
<tr><th><%= form.label :parent_id %></th>
  <td><%= form.text_field :parent_id, id: :page_parent_id %><%
  parent = page&.parent
  if parent
    %> <%= link_to parent.descriptor, parent, class: "icon #{css_classerize(parent)}" %><%
  end %></td></tr>
<tr><th><%= form.label :filename %></th>
  <td><%= form.text_field :filename, id: :page_filename %>
  <br /><strong>Warning:</strong> Changing the filename when updating the page
  can break links to the page.</td></tr>
<tr><th><%= form.label :title %></th>
  <td><%= form.text_field :title, id: :page_title %>
  <br />The Title appears in the title-bar of the web browser.</td></tr>
<tr><th><%= form.label :description %></th>
  <td><%= form.text_area :description, rows: 4, id: :page_description %></td></tr>
<tr><th><%= form.label :content %></th>
  <td><%= form.text_area :content, rows: 16, id: :page_content %></td></tr>
</tbody>
<tfoot><tr><th></th><td><%= form.submit 'Save Page' %></td></tr></tfoot>
</table>
<% end -%>

app/views/pages/_header.html.erb
<%
page ||= nil
parent ||= page&.parent

content_for(:menus) do -%>
<li id="pagesmenu"><%=
  link_to 'Pages', pages_path, title: 'Page Management — create static web pages'
  %><ul>
  <li><%= link_to 'Pages List', pages_path, title: 'List all pages' %></li>
  <li><%= link_to 'Add Page', new_page_path, title: 'Add a new page' %></li>
  <li class="separator"></li>
<%
  if page -%>
  <%=
    tag.li(link_to(
      'Edit Current Page', edit_page_path(page),
      title: "Edit the current page (#{page.descriptor})"
    )) %>
  <%=
    tag.li(link_to(
      'Remove Current Page', delete_page_path(page),
      title: "Remove the current page (#{page.descriptor})"
    )) %>
<%
  else -%>
  <li class="unavailable" title="no current page selected">Edit Current Page</li>
  <li class="unavailable" title="no current page selected">Remove Current Page</li>
<%
  end
-%>
  </ul></li>
<%
end

# Load up the Wayfinder
associated = nil
if page
  actions = {
    update: edit_page_path(page),
    delete: delete_page_path(page),
    create: new_page_path
  }
  associated = [parent] if parent
else
  actions = { create: new_page_path }
end
wayfinder(section: :page, item: page, associated: associated, actions: actions)
-%>

app/views/pages/delete.html.erb
<%= render partial: 'header', locals: { page: @page } -%>
<h1>Delete Page: <%= link_to @page.descriptor, @page %>?</h1>

<%= form_tag(@page, method: :delete) do %>
<p><%= submit_tag 'Delete Page' %></p>
<% end %>

app/views/pages/edit.html.erb
<%= render partial: 'header', locals: { page: @page } -%>
<%= render 'form', page: @page %>

app/views/pages/index.html.erb
<%= render partial: 'header' -%>
<table>
<thead><tr><th>Sitepath</th> <th>Title</th> <th>Actions</th></tr></thead>
<tbody>
<% @pages.each do |page| -%>
<tr>
<td><%= link_to page.sitepath, page %></td>
<td><%= page.title %></td>
<td><%= link_to 'Edit', edit_page_path(page), class: 'icon update' %>
  <%= link_to(
    'Delete', page, method: :delete, data: { confirm: 'Are you sure?' }, class: 'icon destroy'
  ) %></td>
</tr>
<% end -%>
</tbody>
</table>

app/views/pages/new.html.erb
<%= render partial: 'header' -%>
<h1>New Page</h1>

<%= render 'form', page: @page %>

app/views/pages/show.html.erb
<%= render partial: 'header', locals: { page: @page } -%>
<table><tbody>
<tr><th>Title:</th> <td><%= @page.title %></td></tr>
<%
if @parent
  %><tr><th>Parent:</th> <td><%= link_to @parent.descriptor, @parent %></td></tr>
<%
end
-%>
<tr><th>Filename:</th> <td><code><%= @page.filename %></code></td></tr>
<tr><th>Description:</th> <td><%= @page.description %></td></tr>
<tr><th>Content:</th> <td><%= @page.content %></td></tr>
</tbody></table>