config/routes.rb
Rails.application.routes.draw do
  root to: 'routing#root', via: :get

  devise_for :users, skip: [:sessions]
  devise_scope :user do
    # Override paths for login/logout to have simpler paths.
    get 'signin', to: 'devise/sessions#new', as: :new_user_session
    post 'signin', to: 'devise/sessions#create', as: :user_session
    delete 'signout', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  resources :authorities
  resources :pages
  resources :paths
  resources :roles
  resources :users do
    member do
      get 'unlock', action: :unlock_form
      patch 'unlock', action: :unlock
    end
  end

  get 'about' => 'routing#about'
  get 'fresh_install' => 'routing#fresh_install'
  post 'create_initial_records' => 'routing#create_initial_records'
  get '*url' => 'routing#sitepath', format: false
end

app/models/role.rb
require 'filename_validator'

# Defines an access role (authorities) that a user can have.
class Role < ApplicationRecord
  has_many :authorities, dependent: :destroy

  validates :areas, length: { minimum: 1, message: 'must specify at least one area' }
  validates :filename, filename: true
  validates :name, presence: true

  def descriptor
    name
  end
end

app/controllers/roles_controller.rb
require 'role'

# Access to the Role model
class RolesController < ApplicationController
  before_action :check_can_read, only: %i[index show edit]
  before_action :check_can_create, only: %i[new create]
  before_action :check_can_update, only: %i[edit update]
  before_action :check_can_destroy, only: %i[delete destroy]
  before_action :set_role, only: %i[show edit update delete destroy]

  def index
    @roles = Role.all
  end

  def show; end

  def new
    @role = Role.new
  end

  def create
    @role = Role.new(role_params)
    if @role.save
      redirect_to @role, notice: 'Role was successfully created.'
    else
      flash.now.alert = 'Could not save the role with the given values.'
      render :new
    end
  end

  def edit; end

  def update
    if @role.update(role_params)
      redirect_to @role, notice: 'Role was successfully updated.'
    else
      flash.now.alert = 'Could not update the role with the given values.'
      render :edit
    end
  end

  def delete; end

  def destroy
    @role.destroy
    redirect_to roles_url, notice: 'Role was deleted.'
  end

  protected

  def area
    'system'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_role
    @role = Role.find(params.fetch(:id))
  end

  # Only allow a trusted parameter "white list" through.
  def role_params
    trusted = params.require(:role).permit(
      :filename, :name, :description,
      :can_read, :can_create, :can_update, :can_destroy, :can_upload, :can_comment,
      areas: []
    )
    # strip any blank area values
    trusted[:areas]&.delete_if(&:blank?)
    trusted
  end
end

app/views/roles/_form.html.erb
<%
require 'wayground_form_builder'

heading ||= nil

%><%= form_with(model: role, local: true, builder: WaygroundFormBuilder) do |form| %>
<%= show_errors(role) %>
<table><%
if heading
  %><thead><tr><th colspan="2"><%= heading %></th></tr></thead>
<%
end
%><tbody>
<%
# FIXME: Interface for dynamically adding/removing area fields in the Role form
# FIXME: highlight checked permissions in green and bold in the Role form
-%>
<tr><th><%= form.label :name %></th>
  <td><%= form.text_field :name, id: :role_name, class: 'full' %></td></tr>
<tr><th><%= form.label :description %></th>
  <td><%= form.text_area :description, id: :role_description, cols: 40 %></td></tr>
<tr><th><%= form.label :areas, for: 'role_areas_0' %></th>
  <td><%= form.array_field :areas %></td></tr>
<tr><th><%= form.label :filename %></th>
  <td><%= form.text_field :filename, id: :role_filename, class: 'full' %></td></tr>
<tr><th rowspan="9">Permissions</th>
  <td><%= form.check_box :can_read, id: :role_can_read %>
    <%= form.label :can_read, class: 'icon read' %></td></tr>
<tr><td><%= form.check_box :can_create, id: :role_can_create %>
    <%= form.label :can_create, class: 'icon create' %></td></tr>
<tr><td><%= form.check_box :can_update, id: :role_can_update %>
    <%= form.label :can_update, class: 'icon update' %></td></tr>
<tr><td><%= form.check_box :can_destroy, id: :role_can_destroy %>
    <%= form.label :can_destroy, class: 'icon destroy' %></td></tr>
<tr><td><%= form.check_box :can_upload, id: :role_can_upload %>
    <%= form.label :can_upload, class: 'icon upload' %></td></tr>
<tr><td><%= form.check_box :can_comment, id: :role_can_comment %>
    <%= form.label :can_comment, class: 'icon comment' %></td></tr>
</tbody>
<tfoot><tr><th></th><td class="actions"><%= form.submit('Save Role') %></td></tr></tfoot>
</table>
<% end %>

app/views/roles/_header.html.erb
<%
role ||= nil

content_for(:menus) do -%>
<li id="rolesmenu"><%=
  link_to 'Roles', roles_path, title: 'Role configuration — define access restrictions'
  %><ul>
  <li><%= link_to 'Roles List', roles_path, title: 'List all roles' %></li>
  <li><%= link_to 'Add Role', new_role_path, title: 'Add a new role' %></li>
  <li class="separator"></li>
<%
  if role -%>
  <%=
    tag.li(link_to(
      'Edit Current Role', edit_role_path(role),
      title: "Edit the current role (#{role.descriptor})"
    )) %>
  <%=
    tag.li(link_to(
      'Remove Current Role', delete_role_path(role),
      title: "Remove the current role (#{role.descriptor})"
    )) %>
<%
  else -%>
  <li class="unavailable" title="no current role selected">Edit Current Role</li>
  <li class="unavailable" title="no current role selected">Remove Current Role</li>
<%
  end
-%>
  </ul></li>
<%
end

# Load up the Wayfinder
if role
  actions = {
    update: edit_role_path(role),
    delete: delete_role_path(role),
    create: new_role_path
  }
else
  actions = { create: new_role_path }
end
wayfinder(section: :role, item: role, actions: actions)
-%>

app/views/roles/_permission_cell_head.html.erb
<th>Read</th> <th>Create</th> <th>Update</th> <th>Destroy</th> <th>Upload</th> <th>Comment</th>

app/views/roles/_permission_cells.html.erb
<%
# requires role
# optional hide_text (boolean)
hide_text ||= false

def permission(is_true)
  is_true ? 'Can' : 'Can Not'
end
if hide_text
  def full_text(is_true, text)
    tag.span("#{permission(is_true)} #{text}", class: 'no-icon' )
  end
else
  def full_text(is_true, text)
    tag.span("#{permission(is_true)} ", class: 'no-icon' ) + text
  end
end

def permission_table_cell(is_true, label, text)
  truth = is_true ? 'true' : 'false'
  tag.td(
    full_text(is_true, text),
    class: "icon #{label} #{truth}", title: "#{permission(is_true)} #{text}"
  )
end

-%>
<%= permission_table_cell(role.can_read, 'read', 'Read') %>
<%= permission_table_cell(role.can_create, 'create', 'Create') %>
<%= permission_table_cell(role.can_update, 'update', 'Update') %>
<%= permission_table_cell(role.can_destroy, 'destroy', 'Destroy') %>
<%= permission_table_cell(role.can_upload, 'upload', 'Upload') %>
<%= permission_table_cell(role.can_comment, 'comment', 'Comment') %>

app/views/roles/delete.html.erb
<%= render partial: 'header', locals: { role: @role } -%>
<h1>Delete Role: <%= link_to @role.descriptor, @role %>?</h1>

<%= form_tag(@role, method: :delete) do %>
<p><%= submit_tag 'Delete Role' %></p>
<% end %>

app/views/roles/edit.html.erb
<%= render partial: 'header', locals: { role: @role } -%>
<%=
render(
  'form', {
    role: @role,
    heading: "<h1>Editing Role: #{link_to @role.descriptor, @role}</h1>".html_safe
  }
)
%>

app/views/roles/index.html.erb
<%= render partial: 'header' -%>
<table>
<thead>
<tr>
<th>Name</th>
<th>Areas</th>
<th>Filename</th>
<th>Read</th>
<th>Create</th>
<th>Update</th>
<th>Destroy</th>
<th>Upload</th>
<th>Comment</th>
</tr>
</thead>

<tbody>
<%
def permission_table_cell(is_true, label, text, name)
  truth = is_true ? 'true' : 'false'
  permission = is_true ? 'Can ' : 'Can Not '
  tag.td(
    tag.span(permission, class: 'no-icon' ),
    class: "icon #{label} #{truth}",
    title: "#{name.pluralize} #{permission}#{text}"
  )
end
-%>
<% @roles.each do |role|
  name = role.name -%>
<tr>
  <th><%= link_to role.name, role %></th>
  <td><%= role.areas.join(', ') %></td>
  <td><%= role.filename %></td>
  <%= permission_table_cell(role.can_read, 'read', 'Read', name) %>
  <%= permission_table_cell(role.can_create, 'create', 'Create', name) %>
  <%= permission_table_cell(role.can_update, 'update', 'Update', name) %>
  <%= permission_table_cell(role.can_destroy, 'destroy', 'Destroy', name) %>
  <%= permission_table_cell(role.can_upload, 'upload', 'Upload', name) %>
  <%= permission_table_cell(role.can_comment, 'comment', 'Comment', name) %>
</tr>
<% end %>
</tbody>
</table>

app/views/roles/new.html.erb
<%= render partial: 'header' -%>
<%= render 'form', { role: @role, heading: '<h1>New Role</h1>'.html_safe } %>

app/views/roles/show.html.erb
<%= render partial: 'header', locals: { role: @role } -%>
<h1><%= @role.name %></h1>

<%=
description = @role.description
tag.p(description) if description
%>
<p>This role has access to areas:</p>
<ul>
<% @role.areas.each do |area|
  %><%= tag.li(area) %>
<% end -%>
</ul>

<p>(Filename: “<code><%= @role.filename %></code>”)</p>

<table>
<thead><tr><th colspan="9"><h2>Permissions</h2></th></tr></thead>
<tbody>
<tr>
<%= render partial: 'permission_cells', locals: { role: @role } -%>
</tr>
</tbody>
</table>

<%=
render partial: 'authorities/table', locals: { authorities: @role.authorities, exclude_role: true }
%>