config/routes.rb
Rails.application.routes.draw do
  root to: 'routing#root', via: :get

  devise_for :users, skip: [:sessions]
  devise_scope :user do
    # Override paths for login/logout to have simpler paths.
    get 'signin', to: 'devise/sessions#new', as: :new_user_session
    post 'signin', to: 'devise/sessions#create', as: :user_session
    delete 'signout', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  resources :authorities
  resources :pages
  resources :paths
  resources :roles
  resources :users do
    member do
      get 'unlock', action: :unlock_form
      patch 'unlock', action: :unlock
    end
  end

  get 'about' => 'routing#about'
  get 'fresh_install' => 'routing#fresh_install'
  post 'create_initial_records' => 'routing#create_initial_records'
  get '*url' => 'routing#sitepath', format: false
end

app/views/layouts/_errors.html.erb
<%
# requires ‘item’ be an object that has an errors method that works like ActiveRecord.

if item.errors.any?
  heading ||= "#{pluralize(item.errors.count, "error")} prevented this #{item.class.name} from being saved:"
  %><div class="error_messages">
<h2><%= heading %></h2>
<ul>
<%
  item.errors.messages.each do |key, message|
    %><%= tag.li("#{key} #{message.join('; ')}", id: "error-#{key}") %>
<%
  end
  %></ul>
</div>
<%
end -%>

app/views/layouts/_wayfinder.html.erb
<%
section = wayfinder[:section]
item = wayfinder[:item]
associated = wayfinder[:associated]
actions = wayfinder[:actions]

action_name_remap = { create: 'New', update: 'Edit' }

-%>
<div id="wayfinder">
<%
# The current section or item
section_title =
  if section
    section.to_s
  elsif item
    item.class.name.underscore
  end
section_title = section_title.gsub('_', ' ').titleize
icon_class =
  if section
    section.to_s
  elsif item
    css_classerize(item)
  end
if item -%>
<h1><%= tag.span("#{section_title}:", class: "class icon #{icon_class}") %>
<span class="item"><%= item.descriptor %></span></h1>
<%
else -%>
<%= tag.h1(section_title.pluralize, class: "icon #{icon_class}") %>
<%
end

# items associated with current item
if associated -%>
<ul class="associated">
<%
  associated.each do |associate|
    if associate.instance_of? Hash
      section = associate[:section]
      descriptor = associate[:descriptor]
      link = associate[:link]
    else
      # FIXME: add a method for converting class name to css class
      section = css_classerize(associate)
      descriptor = associate.descriptor
      link = associate
    end
    %><%= tag.li(link_to(descriptor, link, class: "icon #{section}")) %>
<%
  end -%>
</ul>
<%
end

if actions -%>
<ul class="actions">
<%
  # TODO: separate actions for the item and actions for the section, then add title attrs
  actions.each do |action, link|
    action_name = action_name_remap[action] || action.capitalize
    %><%= tag.li(link_to(action_name, link, class: "icon #{action}")) %>
<%
  end -%>
</ul>
<% end -%>
</div>

app/views/layouts/application.html.erb
<%
require 'metadata_presenter'

# Parameters - all are optional
#
# page_metadata.title: Used in the <title> meta tag. If blank, defaults to the site title.
# page_metadata.nocache: Boolean, instructs browsers and search engines not to cache page content.
# page_metadata.description: Plain text used as the value for the <meta name="description"> tag.

# Blocks - all are optional. Called with ‘content_for :block_name do … end’.
#
# :head - Goes at the end of the head. Useful for custom meta tags, javascript links, etc.
# :menus - Additional menus (as list items) to be inserted after the root menu.

page_meta = page_metadata
metadata = {
  view: self, title: page_meta.title, description: page_meta.description, nocache: page_meta.nocache
}
metadata_presenter = MetadataPresenter.new(metadata)

-%>
<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8">
<%= metadata_presenter.present_title %>
<%= csrf_meta_tags %>
<%= stylesheet_link_tag 'application', media: 'all' %>
<%= javascript_include_tag 'application' %>
<link rel="icon" href="/favicon.png" type="image/png" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<%= metadata_presenter.present_metatags -%>
<%= yield :head -%>
</head>
<%
if signed_in?
  %><body class="signedin"><%
else
  %><body><%
end
%>

<nav role="navigation"><ul role="menubar">
<li id="rootmenu" role="menu"><%=
  link_to(
    Wayground::Metadata::NAME, root_path,
    title: 'Independent collection of information relevant to elections and government in Calgary.'
  )
  %><ul>
  <li role="menuitem"><%= link_to 'About', about_path %></li>
<% if authority?('page') -%>
  <li class="separator"/>
  <li class="heading">Content Management:</li>
  <li><%= link_to('Pages', pages_path, title: 'Page Management — create static web pages') %></li>
  <li><%= link_to(
    'Paths (& Redirects)', paths_path, title: 'Path setup — define urls for items or redirects'
  ) %></li>
<% end
if authority?('system') -%>
  <li class="separator"/>
  <li class="heading">System Administration:</li>
  <li><%=
    link_to('Users', users_path, title: 'Administration of user login access for this system')
  %></li>
  <li><%= link_to(
    'Roles', roles_path,
    title: 'Administration of the roles (access restrictions) that may be assigned to users'
  ) %></li>
<% end -%>
  </ul></li>
<%= yield :menus -%>
<li id="electionmenu" role="menu"><a>Elections</a><ul>
  <li class="unimplemented">Elections Calgary Info</li>
  </ul></li>
<li id="candidatemenu" role="menu"><a>Candidates</a><ul>
  <li class="heading">Calgary Municipal:</li>
  <li class="unimplemented">Mayor</li>
  <li class="unimplemented">City Council</li>
  <li class="unimplemented">Public School Board</li>
  <li class="unimplemented">Separate School Board</li>
  <li class="unimplemented">All the candidates in one big list</li>
  <li class="separator"/>
  <li class="heading">Alberta Provincial:</li>
  <li class="heading">Canada Federal:</li>
  <li class="separator"/>
  <li class="unimplemented"><span class="icon twitter">Twitter Lists</span></li>
  </ul></li>
<li id="issuemenu" role="menu"><a>Issues</a><ul>
  <li class="unimplemented">Candidate Surveys</li>
  </ul></li>
<li id="calendarmenu" role="menu"><a>Calendar</a><ul>
  <li class="unimplemented">Calendar Grid</li>
  <li class="unimplemented">Event List</li>
  <li class="unimplemented">Subscribe in Your Calendar App</li>
  </ul></li>
<li id="helpmenu" class="unimplemented"><a class="icon help" title="Help and Documentation"><span class="no-icon">Help</span></a><ul>
  <li class="unimplemented" title="Glossary of Terminology, Definitions, and Abbreviations">What does that word, phrase, or abbreviation mean?</li>
  <li class="separator"/>
  <li><%= link_to 'About Calgary Democracy', about_path, title: 'Credits & legal notices' %></li>
  <li><a href="/accountability" title="addresses how we try to fulfill the principles of transparency, openness, equality, and accessibility">Accountability Statement</a></li>
  <li><a href="/privacy" title="explains what information we use, record, and display, about users of this website">Privacy Policy</a></li>
  </ul></li>
<% if signed_in? -%>
<li id="usermenu" class="unimplemented" role="menu"><a class="icon user" title="Your User Account Access"><span class="no-icon">User</span></a><ul>
  <li role="menuitem"><%= link_to 'Sign out', destroy_user_session_path, title: 'Sign out of your current user session', method: :delete, data: { confirm: 'Are you sure you want to sign out?' } %></li></ul></li>
<% end -%>
</ul></nav>

<%
if @wayfinder
  %><%= render partial: 'layouts/wayfinder', locals: { wayfinder: @wayfinder } %><%
end

flash_count = (flash && flash.count) || 0
if flash_count > 0
  %>
<div id="flash"<%= flash_count <= 0 ? ' class="hidden"'.html_safe : '' %>><%
if flash_count > 0
  flash.each do |key, msg|
    %><p class="<%= key %>" role="alert"><%= msg %></p>
<%
  end
end
%></div>
<%
end
-%>

<section id="main" role="main">
<%= yield -%>
</section>

<footer role="contentinfo">
<ul role="navigation">
<li><a href="/about" title="about the Calgary Democracy project">About</a>.</li>
<li><a href="/accountability" title="addresses how we try to fulfill the principles of transparency, openness, equality, and accessibility">Accountability Statement</a>.</li>
<li><a href="/privacy" title="explains what information we use, record, and display, about users of this website">Privacy Policy</a>.</li>
</ul>
<p id="copyright">Copyright ©2007-2017 Grant Neufeld.
<br />Except where otherwise indicated, all text is freely licensed for reuse under a
<a href="http://creativecommons.org/licenses/by/2.5/ca/" class="icon creative-commons">Creative Commons License</a>
requiring attribution for any reuse (including derivative work).
See individual photo/media attributions for licensing details of non-text content.</p>
</footer>

</body>
</html>